### ISSUE TITLE
Handles the new +edns option in dig command

### ISSUE THREAD

**Issue by fourzerofour** [behrooza/dnsd#3]
It appears that newer versson of BIND's `dig` command now defaults to using option `+edns` by default which currently dnsd doesn't understand and cause dnsd to send incorrect dns query and returned unexpected answer to the dig command.

```
% dig @127.0.0.1 google.com A +noall +answer
;; Warning: Message parser reports malformed message packet.
google.com.             299     IN      A       216.58.196.14
google.com.             299     IN      AAAA    2404:6800:4001:806::200e
google.com.             599     IN      MX      40 alt3.aspmx.l.google.com.
google.com.             599     IN      MX      30 alt2.aspmx.l.google.com.
google.com.             21599   IN      NS      ns1.google.com.
google.com.             599     IN      MX      10 aspmx.l.google.com.
google.com.             599     IN      MX      50 alt4.aspmx.l.google.com.
google.com.             599     IN      MX      20 alt1.aspmx.l.google.com.
google.com.             21599   IN      NS      ns3.google.com.
google.com.             21599   IN      NS      ns2.google.com.
```

```
% dig @8.8.8.8 google.com A +noall +answer
google.com.             299     IN      A       172.217.31.78

```

With +noedns option specified, everything behaves as expected again.

```
% dig @127.0.0.1 google.com A +noedns +noall +answer
google.com.             136     IN      A       216.58.199.206
```

More info on this change:

https://deepthought.isc.org/article/AA-01059/0/Why-does-dig-report-one-more-record-in-the-additional-section-of-a-query-response-than-I-am-seeing.html

https://engineering.salesforce.com/why-is-edns-important-for-content-delivery-85f5690744ba

**Comment by kamarya** [comment]
@fourzerofour thank you for reporting the problem. please check out the fix before tagging the new version.
